name: Set environment
description: Set environment variables for the job

inputs:
  environment:
    type: string
    required: false
    default: dev
    description: Environment

runs:
  using: "composite"
  steps:
    - name: Set environment
      run: |
        echo "ENVIRONMENT=${{ inputs.environment }}" >> "${GITHUB_ENV}"
        echo FOO=BAR >> "${GITHUB_ENV}"
      shell: bash
    - name: Print environment
      run: printenv
      shell: bash # run in a new shell process
