name: Debug OIDC token

on:
  workflow_dispatch:
    inputs:
      audience:
        type: string
        required: false
        default: api://AzureADTokenExchange
        description: Audience

jobs:
  debug-oidc-token:
    name: Debug OIDC token
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install jwt-cli 
        run: npm i -g jwt-cli
      - name: Fetch OIDC token
        id: oidc
        run: |
          curl -s -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}" | base64 -w0
          # cat output
          # cat output | base64 -w0
#          echo "token=$(curl -N -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}")" >> ${GITHUB_OUTPUT}
        env:
          AUDIENCE: ${{ inputs.audience }}
      # - name: Print OIDC token
      #   run: |
      #     echo $TOKEN | jq -r .value | base64 -w0
      #     jwt --output json "$(echo ${TOKEN} | jq -r .value)"
      #   env: 
      #     TOKEN: ${{ steps.oidc.outputs.token }}
