name: Reusable workflow 1

on:
  workflow_call:
    inputs:
      logLevel:
        required: true
        type: string

permissions:
  contents: read

jobs:
 create-artifact:
    name: Create artifact
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/