name: Reusable workflow 1

on:
  workflow_call:
    inputs:
      logLevel:
        required: true
        type: string
    secrets:
      github_token:
        required: false

permissions:
  id-token: write
  contents: read 

jobs:
  download-artifact:  
    name: Download artifact
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: random
        path: random/
        github-token: ${{ secrets.github_token }}
        run-id: ${{ github.run_id }}
    - name: Output random number
      run: cat ./random/number

  call-reusable-workflow-2:
    name: Call reusable workflow 2
    permissions:
      id-token: write
      contents: read 
      packages: read
      pull-requests: write
    uses: ./.github/workflows/reusable-workflow-2.yml
    secrets: inherit