name: Reusable workflow 1

on:
  workflow_call:
    inputs:
      logLevel:
        required: true
        type: string

permissions:
  contents: read

jobs:
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
      - name: Output run ID
        run: 'echo "Run ID: ${{ github.run_id }}"'
      

  download-artifact:  
    name: Download artifact
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: pr_number
        path: pr/
        github-token: ${{ github.token}}
        run-id: ${{ github.run_id }}
    needs: upload-artifact