name: Set job enviroment in composite action

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: false
        default: dev
        description: Environment

jobs:
  set-environment:
    name: Set environment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set environment
        uses: ./.github/actions/set-environment
        with:
          environment: ${{ inputs.environment }}
      - name: Print environment
        run: printenv
      - name: Verify environment
        run: | 
          echo $GITHUB_ENV
          grep -q -e "ENVIRONMENT=${{ inputs.environment }}" $GITHUB_ENV && \\ 
          grep -q -e "FOO=BAR" $GITHUB_ENV && \\ 
          echo "Environment verified" || echo "Environment not verified"
