name: Set enviroment using composite action

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: false
        default: dev
        description: Environment

jobs:
  set-environment:
    name: Set environment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set environment
        uses: ./.github/actions/set-environment
        with:
          environment: ${{ inputs.environment }}
      - name: Print environment
        run: printenv
      - name: Verify environment
        run: | 
          grep -q -e "ENVIRONMENT=${{ inputs.environment }}" <(printenv) && \
          grep -q -e "FOO=BAR" <(printenv) && \
          echo "Environment verified" || echo "Environment not verified"
