name: Test skipped

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo "job1"
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job2"
