name: Test if

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"
  
  job2:
    runs-on: ubuntu-latest
    if: true
    needs: job1
    steps:
      - run: |
          echo "job2"
  
  job3: 
    runs-on: ubuntu-latest
    if: false && !cancelled()
    needs: job2
    steps:
      - run: |
          echo "job3"
          echo ${{ needs.job2.result }}
  