name: Test cancelled

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"
          sleep 60
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job2"
          sleep 60
  
  job3: 
    runs-on: ubuntu-latest
    if: !cancelled()
    needs: job2
    steps:
      - run: echo "job3"
  
  job4: 
    runs-on: ubuntu-latest
    if: cancelled()
    needs: job2
    steps:
      - run: echo "job4"