name: Test failure

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"
          exit 1
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job2"
  
  job3: 
    runs-on: ubuntu-latest
    if: success() || failure()
    needs: job2
    steps:
      - run: echo "job3"
  