name: Trigger workflow_run event workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        type: choice
        options:
        - info
        - warning
        - debug
        required: true
        default: warning

permissions:
  contents: read

jobs:
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --user 0
    timeout-minutes: 5
    steps:
      - name: Output log level
        run: 'echo "Log level: ${{ inputs.logLevel }}"'
      - name: Output run ID
        run: 'echo "Run ID: ${{ github.run_id }}"'
      - name: Save random number
        run: |
          mkdir -p ./random
          echo $RANDOM > ./random/number
      - name: Output random number
        run: cat ./random/number
      - uses: actions/upload-artifact@v4
        with:
          name: random
          path: random/

  # A reusable workflow call (workflow_call) won't trigger a workflow_run event
  call-reusable-workflow-1:
    name: Call reusable workflow 1
    permissions:
      id-token: write
      contents: none
      packages: read
      pull-requests: write
      actions: read
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      logLevel: ${{ inputs.logLevel }}
    concurrency: trigger-workflow_run-event-workflow
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: upload-artifact
