name: workflow_run event workflow

on:
  workflow_run:
    workflows: [Trigger workflow_run event workflow]
    types: [completed]
    branches: [main]

jobs:
  output-workflow_run-event-payload:
    name: Output workflow_run event payload
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Output workflow_run event payload
        run: echo "${{ toJson(github.event.workflow_run) }}"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pr_number
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
